### ISSUE TITLE
METADATA: Determine what terms are required

### ISSUE THREAD

**Issue by little9** [curationexperts/cypripedium#114]
@janneller In the UI, some terms are marked as required, like `title` and `keywords`. We can import any we want, but we'll need to be explicit about what terms are required. Could you let us know which terms you would like to be required? Some installations just have `title` and `description`, but you pick whichever terms you want.

**Comment by MPLSFedResearch** [comment]
Would it be bad to have just title? It's the only field in our contendm that is required. We'll have some items that don't have creators (very few), most do not have keywords, and our imported records don't have rights statements.  Only 4 staff members will be adding works in the future.

**Comment by val99erie** [comment]
@MPLSFedResearch I think just a title is fine.  For situations where there are only a few highly skilled users, I think it's best to leave it up to the judgement of the staff to decide which fields to fill in rather than having the form try to enforce a bunch of rules.

The reason we are asking is that by default hyrax requires certain fields, but our importer doesn't, so we were seeing the situation where you import a record using the importer, then use the UI form to edit the record, and the form says that the record is invalid because it's missing some of the required fields.  That was bothering me.  I want to make sure that the form and the importer agree about what a 'valid' record is.
