### ISSUE TITLE
Bulk download of individual works

### ISSUE THREAD

**Issue by little9** [curationexperts/cypripedium#127]
- [x] Create a background job to create a zip file of the files attached to a single work
- [x] When the user clicks download a zip will be created 
- [x] The page displays the status (done, in progress, download)
- [x] The zip's filename is derived from the title and has a timestamp
- [x] I can configure the directory where the zip files will be placed
- [x] Write a file system cleanup story - once the config for the zip file dir has been decided, write a story to make a cron to clean up that directory every 7 days.

DOCUMENTATION:

- [x] Write a README that describes how this feature is supposed to work and the assumptions.  (e.g. The zip files won't be built until a user triggers it.  The UI will show a 'in progress' message, and the user keeps reloading the page until the zip is available.  The zip will get cleaned up every 7 days.  etc)

**Comment by val99erie** [comment]
@janneller Since we are coming up on the deadline for code handoff, I want to narrow down the scope of this story a little.

The way I wrote the code to download the zip file, it currently doesn't do any kind of checks to make sure that the user has the right to download the zip file.  It just assumes that everyone has permission to download a zip.

From what I understand, all the works in your current collections are fully visible to the public, right?  You don't have any restricted works?  Is that assumption correct?

This means that in the future, if you add any restricted works to your repository, you'll need to add some code to the `WorkZipsController` to check that the user is allowed to view a work before you let them download the zip file for that work.

If the assumption that all works are public is wrong, or if you are planning to add restricted works in the near future, then we should spend the time now to add access controls and testing for those controls.  But if all your works are visible, then I'd like to leave the access controls out of scope for this story so that we can finish the rest of the stories before the code handoff deadline.

Let me know what works best for you.

**Comment by MPLSFedResearch** [comment]
This is correct, there will be no restricted works in the collection now or in the future.

**Comment by val99erie** [comment]
I added a task to story #126 to clean up the older zip files.

**Comment by val99erie** [comment]
@janneller When you have time, could you take a look at this README, and let me know if there is anything in there that is confusing or needs more info:
https://github.com/curationexperts/cypripedium/blob/master/README_work_zips.md

When the user views the show page for a work, they'll see a button to create the zip file:
<img width="618" alt="create_button" src="https://user-images.githubusercontent.com/298865/35926154-1fb349a6-0bed-11e8-93bf-770571dba167.png">

.

Or, if the zip file already exists, they'll see a link to download it:
<img width="912" alt="download_link" src="https://user-images.githubusercontent.com/298865/35926178-2a76563a-0bed-11e8-9665-3ac69595e58e.png">

**Comment by MPLSFedResearch** [comment]
I've read it and understand it. It looks so cool! People will be really excited about this feature here.
