### ISSUE TITLE
Upgrade dry-run

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#197]
**STORY**
As a system owner I would like to dry-run the upgrade on a staging environment

**DETAILS**

**ACCEPTANCE**
- [x] Set up our own DCE instance of the current live application
- [x] Populate the sample instance with 
  - [x] Works in collections
  - [x] Works not in collections
  - [x] Collections
  - [x] One Admin set
- [x] Apply the upgrade
- [x] Document the upgrade process (if anything other than deploy)
- [x] Walkthrough snapshot process with Janelle

**Comment by val99erie** [comment]
For the `Document the upgrade process` part of this story, we should put together a formal checklist of the exact commands we need to run during the upgrade.

I'll add some notes here for all the changes I know about so far.  Please update this list or add more comments if you know of any other things we need to do during the release.

- Edit the `solrconfig.xml` and delete the `suggest` functionality as described in these [Hyrax troubleshooting notes](https://github.com/samvera/hyrax/wiki/Troubleshooting-Migration-from-2.0.x-to-2.1.0#fix-performance-issue-caused-by-solr-suggest-after-200-objects-are-in-the-repository), and then you might need to restart solr.  This can be done at any time (before, during, or after the release).  It doesn't need to be timed with the rest of the release.

- Decide which directory to use for the bagit exports.  You can leave it as the default value as defined in the [production config](https://github.com/MPLSFedResearch/cypripedium/blob/master/config/environments/production.rb#L92), or you can set an environment variable `BAG_PATH`.  The environment variable can be set any time before the release.  It doesn't need to happen on release day.

- The hyrax upgrade contains data migrations, so we'll need to migrate the database.  There are [detailed notes about the migrations here](https://github.com/samvera/hyrax/releases/tag/v2.1.0), but those notes are a jumble of development/code changes and changes that we'll need to run in production.  I think this is the full list of commands we'll need to run at release time:

```bash
RAILS_ENV=production bundle exec rails db:migrate

RAILS_ENV=production bundle exec rails hyrax:default_collection_types:create

RAILS_ENV=production bundle exec rails hyrax:migrate:add_collection_type_and_permissions_to_collections
```

- We'll need to re-index all existing work records.  (Because we added new solr fields to support new sorting options and display fields).  Note:  Don't use the reindex task from hyrax/samvera because it uses `AF::Base.reindex_everything`.  We don't want to use that in production.  Use this task instead:

Since this rake task might take awhile to run, you probably want to run it as a background job with nohup so that it won't stop running if you get disconnected from the server.  This command will redirect the output to a file called `solr_reindex.log`, so you can view the log file to see if it is done running.

```bash
RAILS_ENV=production nohup bundle exec rake reindex 2>&1 > solr_reindex.log &
```

- Newer versions of hyrax now have the concept of a "Collection Type".  When you run the migrations, all your existing collections will be given the default collection type, which is called "User Collection".  When you view a collection, there will be a badge on the page that says "User Collection".  That's probably not a good name for the types of collections in cypripedium.  If you want to change that name, you can log in as an admin user:  `Dashboard -> Settings -> Collection Types -> Edit`, and change the title to something else.

**Comment by bess** [comment]
Upgrade checklist here: https://docs.google.com/document/d/1Z312B-cV985rI0ZMidvrkgq3liGZtz5CPv3CNU5eMSs/edit?usp=sharing
