### ISSUE TITLE
Automate AWS backup process

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#288]

**Comment by bess** [comment]
We made a first pass at this but we can't automate this until sidekiq is setup as a system service, because otherwise it won't restart when the box restarts after a backup. So, we know how to do this, we've done a dry run, and it will actually be enabled once we've moved to the new boxes.

- [x] Set up nightly backups to start 
- [x] Document for Jannelle how to go in and adjust frequency
- [x] Document how to delete old backups

**Comment by bess** [comment]
This is now working for qa. We need to set it up for prod.

**Comment by bess** [comment]
This is now setup nightly for production. Docs on how to update frequency are here: https://github.com/MPLSFedResearch/cypripedium/wiki

**Comment by little9** [comment]
https://github.com/MPLSFedResearch/cypripedium/wiki/Deleting-Backups
