### ISSUE TITLE
SPIKE: Research Amazon firewall and rate limiting options

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#331]

**Comment by RachelDCE** [comment]
**STORY**
As a repository manager I would like to know what options Amazon offers for traffic management and prevention of DDOS attacks so that I can evaluate the cost and complexity of implementing these to protect my website. 

**ACCEPTANCE**
- [x] List 2-5 Amazon services addressing these issues 
- [x]  Provide a summary of each capabilities
- [x]  Provide an estimate of the complexity to implement and manage each option

**Comment by little9** [comment]
They are running Amazon WAF which provides anti-bot, XSS, and SQli protection 

![Screenshot_2019-03-15 AWS WAF Shield](https://user-images.githubusercontent.com/4324761/54444044-f579ea00-470f-11e9-9ac8-99babfa0bbc7.png)

There is also Amazon Shield for more comprehensive DDoS protection, but it costs $3000 a month to turn on. 

Since they are running these already, it's easy to implement and manage.

**Comment by mark-dce** [comment]
Not sure why we left this open, so closing it now.
