### ISSUE TITLE
Don't save blacklight searches

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#333]
We seem to be running out of memory immediately after deleting blacklight saved searches. We need to delete those daily so that the database doesn't grow forever and fill up the disk, but the job that deletes them is currently way too expensive. 

See curationexperts/tenejo#217

**Comment by bess** [comment]
```
Mar 13 23:55:01 researchdatabasestaging CRON[20604]: (deploy) CMD (/bin/bash -l -c 'cd /opt/cypripedium/releases/20190301212654 && RAILS_ENV=production bundle exec rake blacklight:delete_old_searches[1] --silent')
Mar 13 23:59:02 researchdatabasestaging cron[1183]: (CRON) error (can't fork)
Mar 14 00:04:11 researchdatabasestaging systemd[1]: apache2.service: Failed to fork: Cannot allocate memory
Mar 14 00:04:14 researchdatabasestaging systemd[1]: apache2.service: Failed to run 'stop' task: Cannot allocate memory
Mar 14 00:04:17 researchdatabasestaging systemd[1]: Stopped LSB: Apache2 web server.
Mar 14 00:04:17 researchdatabasestaging systemd[1]: apache2.service: Unit entered failed state.
Mar 14 00:04:21 researchdatabasestaging systemd[1]: apache2.service: Failed with result 'resources'.
Mar 14 00:04:22 researchdatabasestaging systemd[1]: Stopping LSB: Apache2 web server...
Mar 14 00:04:23 researchdatabasestaging systemd[1]: apache2.service: Failed to fork: Cannot allocate memory
Mar 14 00:04:24 researchdatabasestaging systemd[1]: apache2.service: Failed to run 'start' task: Cannot allocate memory
Mar 14 00:04:25 researchdatabasestaging systemd[1]: Failed to start LSB: Apache2 web server.
Mar 14 00:04:25 researchdatabasestaging systemd[1]: apache2.service: Failed with result 'resources'.
```

**Comment by bess** [comment]
This is the the CPU load during the delete saved searches command:
![load_during_delete_searches.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46e49b9b27bd87bc9de0b1449b59f5982c52224c3a01a239738de63bfd0e39111d0014f9121c4d4eeefc807fa2b63f71dc5902b8d06a5874c63f47a8b1d11cec05a83c990dd4e8e8d51199a26867f5819d4e3614041d8cfd5832a8904ec05af54ef300.png)

**Comment by bess** [comment]
I also start getting `Cannot allocate memory` errors during saved searches delete:

![cannot_allocate_memory_during_saved_searches_delete.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46eb95942d8d97968ee5b34ca75ce491164b227e2616ba147490f121b14544120e191bf82e1b0a15beaad17ee5d96825d6094fb8c3714d3484624bf9ebc60db513bf29df4b85b5bddc49c9bd3c22e08b8f4d681a0c4b8aac5927bc8b099906a214bc141ff1512469f477317646911b772963672eacf8db5581972d.png)

**Comment by bess** [comment]
We added the `delete_old_searches` cron job a year ago:
![delete_old_searches_added.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46ec91962696869680e5bb7cb758f1862a4e22601605a72f7581a164fd52690e050a1de853524d41adf9897da0bf6a25885e5aecd46d5f75946844fabbd017ad1da862da11d1e9e1d30695aa2f2ff58a87453f1b001a8cf75f34a79143c858e406.png)

So why didn't this problem turn up a year ago? I think it's because the task wasn't actually running until we rebuilt the servers, because at that point they got this fix from our ansible build:
![crontab_fix.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46eb86952d9682abb0efb65be611b2843b492d762a10e17132d0e278ef442d58090a4cae10595a44fcf8db7ef3e03f22824e17ff933c0120996048e6edc00db513bb27814e80b3be8f44c2e13d2de38f8d5d73.png)

**Comment by bess** [comment]
As of version 3.0.1, tagged and deployed today, we will no longer save any searches, which eliminates the need to run a `delete_old_searches` cron job, which has also been eliminated. I am also going through and deleting all old searches manually, to reduce the size of the database so it isn't bogged down.
