### ISSUE TITLE
SPIKE: Research QA gem

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#432]
SPIKE: 

Can we use the geographic location field in Hyrax as a model? 
-See Hyrax's existing use of the QA gem + Emory Curate may have examples

**Comment by maxkadel** [comment]
- The QA gem is already being used to provide yml-config-based auto-complete -on data-entry. I think it would be worthwhile to set it up to:
  - Provide a database-based creator authority
  - This creator authority could be linked with the creator model, where the creation of a new creator would also generate a creator authority entry (the authority entries table is fairly generic, so I don't think it would make sense to extend that model to include creator-specific metadata)
  - It might be possible to have the RePEc and VIAF connected to the creator model via QA, but it sounds like that is currently out of scope for this engagement

There is a proof of concept branch using a database table to generate the auto-completes currently provided by the creator.yml authority file. https://github.com/MPLSFedResearch/cypripedium/pull/436 . I think we should not merge it yet because I think it would be easier to integrate with the creator model if we add that first, and then integrate the database-based authority with that.

**Comment by mark-dce** [comment]
This looks like a good plan!

If we get done with the rest of the in-scope work, I bet Janelle would be very happy to have us use any extra time to look at wiring up QA for VIAF lookup.  I'm not sure RePEc has a well defined API endpoint - if it does, I'm sure it's not as widely used as VIAF - so we might not be able to tackle that as easily.  But both seem like end-of-project or future scope.

**Comment by MPLSFedResearch** [comment]
Just an FYI: our records are pulled into RePEc through a different system (fedinprint.org), so we won't need to investigate a RePEc API endpoint at this time. Thanks!
