### ISSUE TITLE
METADATA: add DOI field

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#83]
**STORY**
As a repository admin I would like a place to store DOIs in the metadata for a work.

**ACCEPTANCE**
- [x] There is a DOI field in the edit view that accepts arbitrary string values
- [x] When a DOI has been added to a work, is displays in the show view
- [x] Blank DOIs don't display and empty label

**Comment by mark-dce** [comment]
@janneller can you talk with your archivist and let us know if you have a preferred predicate we should use for the DOI?  We're also happy to do some research and suggest one if folks on your end don't have a preference.

**Comment by MPLSFedResearch** [comment]
We use 10.21034 here for all our works, thanks.

**Comment by val99erie** [comment]
@MPLSFedResearch It looks like you gave us a prefix instead of a predicate.  We're wondering if you have a preference for which predicate to use to store the DOI in fedora.  We like to check because sometimes the archivist has a strong opinion about which predicates to use for the metadata.

For example, we could use DC Identifier: `http://purl.org/dc/terms/identifier`, but I see in the Sargent and Sims collection that some records already use "identifier" for something else, so that won't work.
`<identifier>19750900fedmwp22</identifier>`

**Comment by MPLSFedResearch** [comment]
Sorry, yesterday was a nutty day and I misread that.  If this helps - we don't have DOIs on any of the contentdm records; it'll be for new records. The identifier field in the contentdm XML is being used to match the metadata to the file for import. Contentdm didn't let you keep your file name when you uploaded a file. The identifier field was the only way for us to know which file on our local drives matched the record.

My archivist would like to keep those identifiers in Hyrax, but is fine with having it move away from the identifier predicate and towards something more 'throw away' if that's possible.  Related, we'll be making the DOI visible for public, but not these legacy identifiers.

So, if this is allowed - I could find/replace `identifier` with `legacyFileName` or something that isn't DC for the contentdm XML files, and then the DOIs can have the `identifier` tag. The archivist would prefer this. I hope this makes sense. If so, I'll fix the XML first thing tomorrow morning.

**Comment by val99erie** [comment]
@MPLSFedResearch Ok, thanks for the info.  We'll see if we can find a different predicate for the legacy file name, and then we can specify that the legacy file name shouldn't normally be displayed.

**Comment by val99erie** [comment]
We discussed with @janneller at a meeting this morning, and we decided to do the following:

- We'll find a different predicate for the legacy file name and choose an attribute name to match it.
- Once we know what the new attribute name will be, Janelle will rename the 'identifier' field in Content DM so that it matches the new attribute name.
- Then re-export the records from Content DM, so that the new XML will have the new attribute name for legacy file names instead of 'identifier'.

**Comment by val99erie** [comment]
I realized that we don't need a predicate for the legacy file name on the work record itself.  The attached FileSet record will already have the file name stored on it.  So, I'll tweak the importer to look for a field in the XML called `legacyFileName`, and then I'll work with Janelle to make sure that gets properly renamed in Content DM.

**Comment by val99erie** [comment]
Ok, the code for this story is done.  Before I close the ticket:

@janneller Can you confirm that you have renamed the 'identifier' field in Content DM to 'legacyFileName'.

Once the rename is done, I'll close this ticket

**Comment by MPLSFedResearch** [comment]
We can close the ticket, but for reference the rename will end up being done in the XML file itself in Atom prior to upload. Turns out you can rename the display field name in contentdm, but can't map to a custom field for the XML. I'll be doing a find/replace for identifier instead. This is fine with me, as I'm already adding a few things to the XML file in advance of upload (such as adding collection name at the top and adding different work types when necessary).

Should I update the text XML file with legacyFileName before Friday's call, or will that mess something up?

**Comment by val99erie** [comment]
@MPLSFedResearch Ok thanks.  Yes, go ahead and update your XML file.  As of yesterday, the importer expects the XML tag to be named 'legacyFileName'.  You will be able to run the importer with the old 'identifier' tags, and the metadata will import, but none of the files will get attached to the new records without the  'legacyFileName' in place.
